//! Integration test for MDF 4.20 ##LD (List Data) and ##DV (Data Values) blocks
//! generated by asammdf, verifying end-to-end conformance with a third-party tool.

use std::path::PathBuf;
use std::process::Command;

use falcon_mdf::Mf4File;

fn venv_python() -> Option<PathBuf> {
    // Check in local worktree .venv or main repo .venv
    let candidates = [
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(".venv/bin/python"),
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../falcon_mdf/.venv/bin/python"),
    ];

    candidates.into_iter().find(|c| c.is_file())
}

fn asammdf_available(python: &PathBuf) -> bool {
    Command::new(python)
        .args(["-c", "import asammdf"])
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

#[test]
fn asammdf_4_20_ld_blocks_read_back_accurately() {
    let Some(python) = venv_python() else {
        eprintln!("skipping: no .venv/bin/python found");
        return;
    };
    if !asammdf_available(&python) {
        eprintln!("skipping: asammdf not installed in .venv");
        return;
    }

    let temp = tempfile::Builder::new()
        .suffix(".mf4")
        .tempfile()
        .unwrap();
    let temp_path = temp.path().to_str().unwrap().to_string();

    let script = format!(
        r#"
import numpy as np
from asammdf import MDF, Signal

mdf = MDF(version='4.20')
# Setting fragment size forces asammdf to emit ##LD and ##DV blocks
mdf._write_fragment_size = 800

t = np.linspace(0.0, 10.0, 1000)
s = np.sin(t)
sig = Signal(samples=s, timestamps=t, name='SineChannel', unit='V')
mdf.append(sig)

mdf.save(r'{temp_path}', overwrite=True)
"#
    );

    let status = Command::new(&python)
        .args(["-c", &script])
        .status()
        .expect("run python generator");
    assert!(status.success(), "asammdf script failed");

    let file_bytes = std::fs::read(temp.path()).expect("read generated mf4");
    assert!(
        file_bytes.windows(4).any(|w| w == b"##LD"),
        "generated file must contain ##LD block"
    );
    assert!(
        file_bytes.windows(4).any(|w| w == b"##DV"),
        "generated file must contain ##DV block"
    );

    let mdf = Mf4File::open(temp.path()).expect("falcon_mdf should open asammdf 4.20 file");
    let ch = mdf
        .find_channel("SineChannel")
        .expect("SineChannel must exist");
    let sig = mdf.signal(ch).expect("read signal");

    assert_eq!(sig.len(), 1000);
    let values = sig.values_f64().expect("values f64");
    assert_eq!(values.len(), 1000);

    for (i, value) in values.iter().enumerate() {
        let expected_t = (i as f64) * 10.0 / 999.0;
        let expected_v = expected_t.sin();

        assert!(
            (value - expected_v).abs() < 1e-5,
            "value mismatch at {i}: got {value}, expected {expected_v}"
        );
    }
}
