//! The bus panel's Ethernet and FlexRay exports, over logs written by
//! `ihedvall/mdflib` rather than by this crate. The fixtures are generated by
//! `scripts/make_mdflib_bus_fixtures.sh`; the values checked here follow the
//! formulas in `scripts/mdflib_bus_fixtures/main.cpp`.

use std::path::{Path, PathBuf};

use falcon_mdf::Mf4File;
use falcon_mdf_gui::panels::bus::{write_eth_csv, write_flexray_csv};

fn fixture(name: &str) -> Option<PathBuf> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../test_data/generated")
        .join(name);
    if path.is_file() {
        Some(path)
    } else {
        eprintln!("skipping: {name} missing; run scripts/make_mdflib_bus_fixtures.sh");
        None
    }
}

fn group<'a>(file: &'a Mf4File, name: &str) -> &'a falcon_mdf::ChannelGroup {
    file.data_groups()
        .iter()
        .flat_map(|dg| dg.channel_groups.iter())
        .find(|cg| cg.acquisition_name == name)
        .expect("frame group present")
}

#[test]
fn ethernet_frames_export_with_addresses_and_ether_type() {
    let Some(path) = fixture("mdflib_ethernet.mf4") else {
        return;
    };
    let file = Mf4File::open(path).unwrap();
    let frames = file.eth_frames(group(&file, "ETH_Frame")).unwrap();
    let out = tempfile::NamedTempFile::new().unwrap();
    write_eth_csv(&frames, Some(&[0, 5]), out.path()).unwrap();
    let text = std::fs::read_to_string(out.path()).unwrap();
    let lines: Vec<&str> = text.lines().collect();
    assert_eq!(
        lines[0],
        "index,time_ms,source,destination,ether_type_hex,bus_channel,length,data_hex"
    );
    // Frame 5: MACs end in 05, EtherType 0x0805, bus 5 % 3 + 1 = 3, and a
    // 6-byte payload (5 % 9 + 1) of bytes 35..=40.
    let row: Vec<&str> = lines[2].split(',').collect();
    assert_eq!(row[0], "5");
    assert_eq!(row[2], "02:00:00:00:00:05");
    assert_eq!(row[3], "02:ff:00:00:00:05");
    assert_eq!(row[4], "0x0805");
    assert_eq!(row[5], "3");
    assert_eq!(row[6], "6");
    assert_eq!(row[7], "23 24 25 26 27 28");
    assert_eq!(lines.len(), 3, "header plus the two selected frames");
}

#[test]
fn flexray_frames_export_with_cycle_and_flags() {
    let Some(path) = fixture("mdflib_flexray.mf4") else {
        return;
    };
    let file = Mf4File::open(path).unwrap();
    let frames = file.flexray_frames(group(&file, "FLX_Frame")).unwrap();
    let out = tempfile::NamedTempFile::new().unwrap();
    write_flexray_csv(&frames, None, out.path()).unwrap();
    let text = std::fs::read_to_string(out.path()).unwrap();
    let lines: Vec<&str> = text.lines().collect();
    assert_eq!(lines.len(), 1 + 24);
    // Frame 5: ID 105, cycle 15, bus 2, a null frame (5 % 6 == 5), neither
    // sync nor startup, and no payload (2 * (5 % 5) = 0).
    let row: Vec<&str> = lines[6].split(',').collect();
    assert_eq!(
        &row[0..9],
        ["5", row[1], "105", "15", "2", "1", "0", "0", "0"]
    );
    // Frame 8: sync (8 % 4 == 0) and startup (8 % 8 == 0), 6 payload bytes.
    let row: Vec<&str> = lines[9].split(',').collect();
    assert_eq!(&row[5..9], ["0", "1", "1", "6"]);
}
